version: '3'

services:

  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/docker/www:/var/www/
      - /var/docker/nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /var/docker/nginx/etc/nginx/conf.d:/etc/nginx/conf.d
      # - /var/docker/nginx/var/log/nginx:/var/log/nginx
    depends_on:
      # - php5.6
      - php7.0
      - phpmyadmin

  mysql:
    image: lizsdocker/mariadb:latest
    # image: mysql
    ports:
      - 3306:3306
    volumes:
      - /var/docker/mariadb/initdb.d:/docker-entrypoint-initdb.d
      - /var/docker/mariadb/etc/mysql/my.cnf:/etc/mysql/my.cnf
      - /var/docker/mariadb/etc/mysql/conf.d:/etc/mysql/conf.d
      - mariadb-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    depends_on:
      - mysql

  # php5.6:
  #   image: lizsdocker/php:5.6-fpm
  #   volumes:
  #     - /var/docker/www:/var/www/html
  #     - /var/docker/php/5.6/usr/local/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf
  #     - /var/docker/php/5.6/usr/local/etc/php-fpm.d:/usr/local/etc/php-fpm.d
  #   depends_on:
  #     - mysql

  php7.0:
    image: lizsdocker/php:7.0-fpm
    volumes:
      - /var/docker/www:/var/www/html
      - /var/docker/php/7.0/usr/local/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - /var/docker/php/7.0/usr/local/etc/php-fpm.d:/usr/local/etc/php-fpm.d
    depends_on:
      - mysql

    # mongodb:
  #   image: mongo:latest
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - /var/docker/mongodb/etc/mongod.conf.orig:/etc/mongod.conf.orig

  redis:
    image: lizsdocker/redis:latest
    ports:
      - 6379:6379
    volumes:
      - /var/docker/redis/etc/redis/redis.conf:/etc/redis/redis.conf
      - redis-data:/data

  # this container do nothing, but preventing to delete volume data by mistake.
  # persistence:
  #   image: ubuntu:18.04
  #   volumes:
  #     - mariadb-data:/var/lib/mysql

  # myproject:
  #   image: myproject:1.0
  #   # ports:
  #   #   - 8000:8000
  #   volumes:
  #     - /var/docker/www/myproject:/var/app
  #   depends_on:
  #     - mysql
  #   environment:
  #     - APP=myproject
  #     - PORT=8000
  #     - GUNICORN_CMD_ARGS="--bind=127.0.0.1:8000 --workers=4 --worker-class=eventlet --error-logfile /var/log/error.log --access-logfile /var/log/access.log"

volumes:
  mariadb-data:
  redis-data:
  # mysql-data:
  # mongo-data:

